function __global_object_depths() {
	// Initialise the global array that allows the lookup of the depth of a given object
	// GM2.0 does not have a depth on objects so on import from 1.x a global array is created
	// NOTE: MacroExpansion is used to insert the array initialisation at import time
	gml_pragma( "global", "__global_object_depths()");

	// insert the generated arrays here
	global.__objectDepths[0] = 0; // obj_lvl_menu
	global.__objectDepths[1] = 0; // obj_pause
	global.__objectDepths[2] = 0; // obj_refresh
	global.__objectDepths[3] = -10; // obj_lvls_menu
	global.__objectDepths[4] = -10; // obj_sabade_tokhm
	global.__objectDepths[5] = -10; // obj_lvl_next
	global.__objectDepths[6] = -10; // obj_score
	global.__objectDepths[7] = -9; // obj_panel_pause
	global.__objectDepths[8] = -10; // obj_continue
	global.__objectDepths[9] = 0; // obj_chapter_star
	global.__objectDepths[10] = -10; // obj_fail_icon
	global.__objectDepths[11] = -10; // obj_refreshS
	global.__objectDepths[12] = -10; // obj_menu_kharchang
	global.__objectDepths[13] = -12; // obj_help
	global.__objectDepths[14] = -12; // obj_feature_help
	global.__objectDepths[15] = -12; // obj_water_fly_help
	global.__objectDepths[16] = 0; // obj_scnario_help
	global.__objectDepths[17] = 0; // obj_facebook_1
	global.__objectDepths[18] = 0; // obj_sounds
	global.__objectDepths[19] = 0; // obj_infos
	global.__objectDepths[20] = 20; // obj_abr_m
	global.__objectDepths[21] = 0; // obj_cheragh_o_f
	global.__objectDepths[22] = -1; // obj_cheragh_play
	global.__objectDepths[23] = 0; // obj_cheragh_tablo
	global.__objectDepths[24] = -4; // obj_play_1
	global.__objectDepths[25] = 5; // obj_LifeInEgg
	global.__objectDepths[26] = -20; // obj_about_us
	global.__objectDepths[27] = 0; // obj_sabze
	global.__objectDepths[28] = 0; // obj_back_fasl
	global.__objectDepths[29] = 2; // obj_rast_faslJJ
	global.__objectDepths[30] = 2; // obj_rast_lvlJ
	global.__objectDepths[31] = 2; // obj_rast_faslJ
	global.__objectDepths[32] = 2; // obj_chap_lvlJ
	global.__objectDepths[33] = 0; // obj_tokhmJooje
	global.__objectDepths[34] = 10; // obj_barg1
	global.__objectDepths[35] = 3; // obj_barg2
	global.__objectDepths[36] = 3; // obj_barg3
	global.__objectDepths[37] = 6; // obj_tokhmGhoflP
	global.__objectDepths[38] = 0; // obj_chap_faslP
	global.__objectDepths[39] = 2; // obj_rast_faslPPP
	global.__objectDepths[40] = 2; // obj_rast_lvlP
	global.__objectDepths[41] = 2; // obj_chap_lvlP
	global.__objectDepths[42] = 3; // obj_rast_faslP
	global.__objectDepths[43] = 0; // obj_back_faslP
	global.__objectDepths[44] = 0; // obj_emtiazP
	global.__objectDepths[45] = 0; // obj_Bg_setare2
	global.__objectDepths[46] = 0; // obj_setare2
	global.__objectDepths[47] = 0; // obj_setare_t2
	global.__objectDepths[48] = 0; // obj_Bg_setare
	global.__objectDepths[49] = 0; // obj_tokhmLakposht
	global.__objectDepths[50] = 0; // obj_chap_faslLLL
	global.__objectDepths[51] = 2; // obj_rast_faslLLL
	global.__objectDepths[52] = 2; // obj_rast_lvlL
	global.__objectDepths[53] = 2; // obj_rast_faslL
	global.__objectDepths[54] = 2; // obj_chap_lvlL
	global.__objectDepths[55] = 2; // obj_chap_faslL
	global.__objectDepths[56] = 0; // obj_back_faslL
	global.__objectDepths[57] = 0; // obj_emtiazL
	global.__objectDepths[58] = 5; // obj_tokhmDaynasor
	global.__objectDepths[59] = 3; // obj_morgh
	global.__objectDepths[60] = 0; // obj_chap_faslD
	global.__objectDepths[61] = 2; // obj_rast_faslD
	global.__objectDepths[62] = 2; // obj_rast_lvlD
	global.__objectDepths[63] = 2; // obj_chap_lvlD
	global.__objectDepths[64] = 0; // obj_back_faslD
	global.__objectDepths[65] = 0; // obj_emtiazD
	global.__objectDepths[66] = 0; // obj_tokhmEjdeha
	global.__objectDepths[67] = 0; // obj_chap_faslE
	global.__objectDepths[68] = 2; // onj_rast_lvlE
	global.__objectDepths[69] = 2; // obj_chap_lvlE
	global.__objectDepths[70] = 0; // obj_emtiazE
	global.__objectDepths[71] = 0; // obj_back_faslE
	global.__objectDepths[72] = 0; // obj_bute
	global.__objectDepths[73] = 0; // obj_entekhab_fasl
	global.__objectDepths[74] = 0; // obj_select_khali
	global.__objectDepths[75] = 0; // obj_select_por
	global.__objectDepths[76] = 0; // obj_jooje
	global.__objectDepths[77] = 0; // obj_entekhab_levelP
	global.__objectDepths[78] = 0; // obj_entekhab_levelL
	global.__objectDepths[79] = 0; // obj_entekhab_levelD
	global.__objectDepths[80] = 0; // obj_entekhab_levelE
	global.__objectDepths[81] = 0; // obj_back_f
	global.__objectDepths[82] = 0; // obj_back_menu
	global.__objectDepths[83] = 0; // obj_abr_fasl
	global.__objectDepths[84] = 0; // ob_bg_jahat
	global.__objectDepths[85] = 0; // obj_egg_ph
	global.__objectDepths[86] = 0; // obj_egg_base
	global.__objectDepths[87] = -1000; // obj_egg
	global.__objectDepths[88] = 0; // obj_egg_physics_off
	global.__objectDepths[89] = -3; // obj_egg_physics_on
	global.__objectDepths[90] = 0; // obj_egg_scaled_big
	global.__objectDepths[91] = 0; // obj_egg_scaled_small
	global.__objectDepths[92] = 0; // obj_smoke
	global.__objectDepths[93] = 0; // obj_dolakh
	global.__objectDepths[94] = 0; // obj_phy_negative
	global.__objectDepths[95] = 0; // obj_kharchang
	global.__objectDepths[96] = 0; // obj_kharposht
	global.__objectDepths[97] = 0; // obj_platipos
	global.__objectDepths[98] = 0; // obj_maar
	global.__objectDepths[99] = 0; // obj_marmoolak
	global.__objectDepths[100] = 0; // obj_phy
	global.__objectDepths[101] = 0; // obj_solid
	global.__objectDepths[102] = 4; // obj_meygoo
	global.__objectDepths[103] = 4; // obj_kerm
	global.__objectDepths[104] = 4; // obj_kafshdoozak
	global.__objectDepths[105] = 0; // obj_kerm_anm
	global.__objectDepths[106] = 0; // obj_mahi
	global.__objectDepths[107] = 0; // obj_malakh
	global.__objectDepths[108] = 0; // obj_partabgar_mthrk
	global.__objectDepths[109] = 0; // obj_partabgar_sbt
	global.__objectDepths[110] = 2; // obj_sling_scope
	global.__objectDepths[111] = 0; // obj_egger_controller_5
	global.__objectDepths[112] = 0; // obj_sling_scope_anim
	global.__objectDepths[113] = 0; // obj_all_controllers
	global.__objectDepths[114] = 0; // obj_bridge_control
	global.__objectDepths[115] = 0; // obj_drag_ctrl
	global.__objectDepths[116] = 0; // obj_fly
	global.__objectDepths[117] = 0; // obj_gaurd
	global.__objectDepths[118] = 0; // obj_gravity
	global.__objectDepths[119] = 0; // obj_scale_big
	global.__objectDepths[120] = 0; // obj_scale_small
	global.__objectDepths[121] = -10000; // obj_th_gaurd
	global.__objectDepths[122] = 0; // obj_th_feature_base
	global.__objectDepths[123] = -10000; // obj_th_water_fly
	global.__objectDepths[124] = -10000; // obj_th_scale_small
	global.__objectDepths[125] = -10000; // obj_th_scale_big
	global.__objectDepths[126] = -10000; // obj_th_speed
	global.__objectDepths[127] = -10000; // obj_th_fly
	global.__objectDepths[128] = -10000; // obj_th_bomb
	global.__objectDepths[129] = 0; // obj_speed
	global.__objectDepths[130] = 0; // obj_water_fly
	global.__objectDepths[131] = 0; // obj_feature_base
	global.__objectDepths[132] = -1000; // obj_panel_center
	global.__objectDepths[133] = -4; // obj_water_fly_controller
	global.__objectDepths[134] = 0; // obj_fly_controller
	global.__objectDepths[135] = 0; // obj_bomb
	global.__objectDepths[136] = 0; // obj_gaurd_controller
	global.__objectDepths[137] = 0; // obj_harekatAngosht
	global.__objectDepths[138] = 0; // obj_stars
	global.__objectDepths[139] = 0; // obj_bridge
	global.__objectDepths[140] = 0; // obj_chicken
	global.__objectDepths[141] = 0; // obj_lakposht
	global.__objectDepths[142] = 0; // obj_daynasor_inlvl
	global.__objectDepths[143] = 0; // obj_pangooan
	global.__objectDepths[144] = 0; // obj_star
	global.__objectDepths[145] = 0; // obj_pin
	global.__objectDepths[146] = 0; // obj_line
	global.__objectDepths[147] = 0; // obj_choob
	global.__objectDepths[148] = 0; // obj_wood_top
	global.__objectDepths[149] = 0; // obj_hobab
	global.__objectDepths[150] = 0; // obj_setare_jaragha
	global.__objectDepths[151] = 0; // obj_egg_break_anim
	global.__objectDepths[152] = 0; // obj_wood_base
	global.__objectDepths[153] = 0; // obj_collisionable_base
	global.__objectDepths[154] = 0; // obj_base_anim
	global.__objectDepths[155] = 0; // obj_base_star
	global.__objectDepths[156] = -9; // obj_QuitMenu
	global.__objectDepths[157] = -100; // obj_No_dontQuit
	global.__objectDepths[158] = -100; // obj_Yes_Quit
	global.__objectDepths[159] = 0; // obj_crash
	global.__objectDepths[160] = 0; // obj_shake
	global.__objectDepths[161] = -100; // obj_textbox_code
	global.__objectDepths[162] = -9; // obj_checkCodePopUp
	global.__objectDepths[163] = -100; // obj_okButtonCode
	global.__objectDepths[164] = -100; // obj_cancelButtonCode
	global.__objectDepths[165] = 0; // obj_message
	global.__objectDepths[166] = 0; // object1
	global.__objectDepths[167] = 0; // obj_debug
	global.__objectDepths[168] = 0; // obj_drag_test
	global.__objectDepths[169] = 0; // obj_textbox_phone
	global.__objectDepths[170] = 0; // obj_text
	global.__objectDepths[171] = 0; // obj_button
	global.__objectDepths[172] = 0; // obj_time


	global.__objectNames[0] = "obj_lvl_menu";
	global.__objectNames[1] = "obj_pause";
	global.__objectNames[2] = "obj_refresh";
	global.__objectNames[3] = "obj_lvls_menu";
	global.__objectNames[4] = "obj_sabade_tokhm";
	global.__objectNames[5] = "obj_lvl_next";
	global.__objectNames[6] = "obj_score";
	global.__objectNames[7] = "obj_panel_pause";
	global.__objectNames[8] = "obj_continue";
	global.__objectNames[9] = "obj_chapter_star";
	global.__objectNames[10] = "obj_fail_icon";
	global.__objectNames[11] = "obj_refreshS";
	global.__objectNames[12] = "obj_menu_kharchang";
	global.__objectNames[13] = "obj_help";
	global.__objectNames[14] = "obj_feature_help";
	global.__objectNames[15] = "obj_water_fly_help";
	global.__objectNames[16] = "obj_scnario_help";
	global.__objectNames[17] = "obj_facebook_1";
	global.__objectNames[18] = "obj_sounds";
	global.__objectNames[19] = "obj_infos";
	global.__objectNames[20] = "obj_abr_m";
	global.__objectNames[21] = "obj_cheragh_o_f";
	global.__objectNames[22] = "obj_cheragh_play";
	global.__objectNames[23] = "obj_cheragh_tablo";
	global.__objectNames[24] = "obj_play_1";
	global.__objectNames[25] = "obj_LifeInEgg";
	global.__objectNames[26] = "obj_about_us";
	global.__objectNames[27] = "obj_sabze";
	global.__objectNames[28] = "obj_back_fasl";
	global.__objectNames[29] = "obj_rast_faslJJ";
	global.__objectNames[30] = "obj_rast_lvlJ";
	global.__objectNames[31] = "obj_rast_faslJ";
	global.__objectNames[32] = "obj_chap_lvlJ";
	global.__objectNames[33] = "obj_tokhmJooje";
	global.__objectNames[34] = "obj_barg1";
	global.__objectNames[35] = "obj_barg2";
	global.__objectNames[36] = "obj_barg3";
	global.__objectNames[37] = "obj_tokhmGhoflP";
	global.__objectNames[38] = "obj_chap_faslP";
	global.__objectNames[39] = "obj_rast_faslPPP";
	global.__objectNames[40] = "obj_rast_lvlP";
	global.__objectNames[41] = "obj_chap_lvlP";
	global.__objectNames[42] = "obj_rast_faslP";
	global.__objectNames[43] = "obj_back_faslP";
	global.__objectNames[44] = "obj_emtiazP";
	global.__objectNames[45] = "obj_Bg_setare2";
	global.__objectNames[46] = "obj_setare2";
	global.__objectNames[47] = "obj_setare_t2";
	global.__objectNames[48] = "obj_Bg_setare";
	global.__objectNames[49] = "obj_tokhmLakposht";
	global.__objectNames[50] = "obj_chap_faslLLL";
	global.__objectNames[51] = "obj_rast_faslLLL";
	global.__objectNames[52] = "obj_rast_lvlL";
	global.__objectNames[53] = "obj_rast_faslL";
	global.__objectNames[54] = "obj_chap_lvlL";
	global.__objectNames[55] = "obj_chap_faslL";
	global.__objectNames[56] = "obj_back_faslL";
	global.__objectNames[57] = "obj_emtiazL";
	global.__objectNames[58] = "obj_tokhmDaynasor";
	global.__objectNames[59] = "obj_morgh";
	global.__objectNames[60] = "obj_chap_faslD";
	global.__objectNames[61] = "obj_rast_faslD";
	global.__objectNames[62] = "obj_rast_lvlD";
	global.__objectNames[63] = "obj_chap_lvlD";
	global.__objectNames[64] = "obj_back_faslD";
	global.__objectNames[65] = "obj_emtiazD";
	global.__objectNames[66] = "obj_tokhmEjdeha";
	global.__objectNames[67] = "obj_chap_faslE";
	global.__objectNames[68] = "onj_rast_lvlE";
	global.__objectNames[69] = "obj_chap_lvlE";
	global.__objectNames[70] = "obj_emtiazE";
	global.__objectNames[71] = "obj_back_faslE";
	global.__objectNames[72] = "obj_bute";
	global.__objectNames[73] = "obj_entekhab_fasl";
	global.__objectNames[74] = "obj_select_khali";
	global.__objectNames[75] = "obj_select_por";
	global.__objectNames[76] = "obj_jooje";
	global.__objectNames[77] = "obj_entekhab_levelP";
	global.__objectNames[78] = "obj_entekhab_levelL";
	global.__objectNames[79] = "obj_entekhab_levelD";
	global.__objectNames[80] = "obj_entekhab_levelE";
	global.__objectNames[81] = "obj_back_f";
	global.__objectNames[82] = "obj_back_menu";
	global.__objectNames[83] = "obj_abr_fasl";
	global.__objectNames[84] = "ob_bg_jahat";
	global.__objectNames[85] = "obj_egg_ph";
	global.__objectNames[86] = "obj_egg_base";
	global.__objectNames[87] = "obj_egg";
	global.__objectNames[88] = "obj_egg_physics_off";
	global.__objectNames[89] = "obj_egg_physics_on";
	global.__objectNames[90] = "obj_egg_scaled_big";
	global.__objectNames[91] = "obj_egg_scaled_small";
	global.__objectNames[92] = "obj_smoke";
	global.__objectNames[93] = "obj_dolakh";
	global.__objectNames[94] = "obj_phy_negative";
	global.__objectNames[95] = "obj_kharchang";
	global.__objectNames[96] = "obj_kharposht";
	global.__objectNames[97] = "obj_platipos";
	global.__objectNames[98] = "obj_maar";
	global.__objectNames[99] = "obj_marmoolak";
	global.__objectNames[100] = "obj_phy";
	global.__objectNames[101] = "obj_solid";
	global.__objectNames[102] = "obj_meygoo";
	global.__objectNames[103] = "obj_kerm";
	global.__objectNames[104] = "obj_kafshdoozak";
	global.__objectNames[105] = "obj_kerm_anm";
	global.__objectNames[106] = "obj_mahi";
	global.__objectNames[107] = "obj_malakh";
	global.__objectNames[108] = "obj_partabgar_mthrk";
	global.__objectNames[109] = "obj_partabgar_sbt";
	global.__objectNames[110] = "obj_sling_scope";
	global.__objectNames[111] = "obj_egger_controller_5";
	global.__objectNames[112] = "obj_sling_scope_anim";
	global.__objectNames[113] = "obj_all_controllers";
	global.__objectNames[114] = "obj_bridge_control";
	global.__objectNames[115] = "obj_drag_ctrl";
	global.__objectNames[116] = "obj_fly";
	global.__objectNames[117] = "obj_gaurd";
	global.__objectNames[118] = "obj_gravity";
	global.__objectNames[119] = "obj_scale_big";
	global.__objectNames[120] = "obj_scale_small";
	global.__objectNames[121] = "obj_th_gaurd";
	global.__objectNames[122] = "obj_th_feature_base";
	global.__objectNames[123] = "obj_th_water_fly";
	global.__objectNames[124] = "obj_th_scale_small";
	global.__objectNames[125] = "obj_th_scale_big";
	global.__objectNames[126] = "obj_th_speed";
	global.__objectNames[127] = "obj_th_fly";
	global.__objectNames[128] = "obj_th_bomb";
	global.__objectNames[129] = "obj_speed";
	global.__objectNames[130] = "obj_water_fly";
	global.__objectNames[131] = "obj_feature_base";
	global.__objectNames[132] = "obj_panel_center";
	global.__objectNames[133] = "obj_water_fly_controller";
	global.__objectNames[134] = "obj_fly_controller";
	global.__objectNames[135] = "obj_bomb";
	global.__objectNames[136] = "obj_gaurd_controller";
	global.__objectNames[137] = "obj_harekatAngosht";
	global.__objectNames[138] = "obj_stars";
	global.__objectNames[139] = "obj_bridge";
	global.__objectNames[140] = "obj_chicken";
	global.__objectNames[141] = "obj_lakposht";
	global.__objectNames[142] = "obj_daynasor_inlvl";
	global.__objectNames[143] = "obj_pangooan";
	global.__objectNames[144] = "obj_star";
	global.__objectNames[145] = "obj_pin";
	global.__objectNames[146] = "obj_line";
	global.__objectNames[147] = "obj_choob";
	global.__objectNames[148] = "obj_wood_top";
	global.__objectNames[149] = "obj_hobab";
	global.__objectNames[150] = "obj_setare_jaragha";
	global.__objectNames[151] = "obj_egg_break_anim";
	global.__objectNames[152] = "obj_wood_base";
	global.__objectNames[153] = "obj_collisionable_base";
	global.__objectNames[154] = "obj_base_anim";
	global.__objectNames[155] = "obj_base_star";
	global.__objectNames[156] = "obj_QuitMenu";
	global.__objectNames[157] = "obj_No_dontQuit";
	global.__objectNames[158] = "obj_Yes_Quit";
	global.__objectNames[159] = "obj_crash";
	global.__objectNames[160] = "obj_shake";
	global.__objectNames[161] = "obj_textbox_code";
	global.__objectNames[162] = "obj_checkCodePopUp";
	global.__objectNames[163] = "obj_okButtonCode";
	global.__objectNames[164] = "obj_cancelButtonCode";
	global.__objectNames[165] = "obj_message";
	global.__objectNames[166] = "object1";
	global.__objectNames[167] = "obj_debug";
	global.__objectNames[168] = "obj_drag_test";
	global.__objectNames[169] = "obj_textbox_phone";
	global.__objectNames[170] = "obj_text";
	global.__objectNames[171] = "obj_button";
	global.__objectNames[172] = "obj_time";


	// create another array that has the correct entries
	var len = array_length_1d(global.__objectDepths);
	global.__objectID2Depth = [];
	for( var i=0; i<len; ++i ) {
		var objID = asset_get_index( global.__objectNames[i] );
		if (objID >= 0) {
			global.__objectID2Depth[ objID ] = global.__objectDepths[i];
		} // end if
	} // end for


}
